spring:
  application:
    name: eureka-server
  pid:
    file: D:/taobao_data/${spring.application.name}/pid/application.pid
server:
  port: 7000

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
        exclude: '*'
      base-path: /
    enabled-by-default: false

eureka:
  server:
    #测试环境关闭自我保护(生产打开)
    enable-self-preservation: false
  client:
    #只有一个server就不开启注册自己了
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/