spring:
  jpa:
    database: mysql
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/license?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
    username: "{cipher}8cb9849b3f8922e990a24460bb48e5743c0d9fa8ca8699c2cc628f0985dd1187"
    password: "{cipher}cfb904db7b8ac48c9c8774808f5f43e8c24de63f7a88fc6afe912911c313a84c"
    tomcat:
      test-while-idle: true
      validation-query: SELECT 3
  redis:
    host: 192.168.123.198
    port: 6379
    password: "{cipher}ac4487e612cee555f45e59d14c0fcc7a043dbbc834456c6f71d6c6b0074732cd"
    connect-timeout: 10s
    jedis:
      pool:
        max-active: 10
        min-idle: 10
        max-idle: 10
        max-wait: 10ms