server:
  port: 8081
  servlet:
    context-path: /config-service
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:H:/dev_workspace/learnspringcloud/config-location/{application}