server:
  port: 8081
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:G:/Users/zhaojn/IdeaProjects/learnspringcloud/config-location/{application}