server:
  port: 8080
  servlet:
    context-path: /config-service
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: http://${spring.cloud.config.server.git.username}@192.168.123.198:10080/r/online_platform_config.git
          default-label: master
          search-paths: /**
          username: "{cipher}c98383494897e557bb661f7fee48a83f5ff4e260dd5deca10c617949b77b84d3"
          password: "{cipher}529e1d7de4c447408a9694d561c3fc91adc6fd146492328aaa04a75aab1a81cc"
management:
  endpoints:
    web:
      exposure:
        include: refresh,info, health